### ISSUE TITLE
Twitch chat

### ISSUE THREAD

**Issue by RockoKaine** [Etuldan/MidiControl#1]
I connected my account, but I can’t get the twitch chat to send the message. Under the twitch chat option I put in the url to my twitch, but when I press the midi key the chat never sends.

**Comment by Etuldan** [comment]
Be sure to get the latest build, as I revoked the private twitch api Key.
Also, in the twitch channel inputbox, you just have to enter your channel (or username), not the full url.

**Comment by RockoKaine** [comment]
Okay that was it, I needed to use my username instead of url. Thank you. Is there more documentation other than the read me? I love this by the way
