### ISSUE TITLE
1rst twitch chat input not working

### ISSUE THREAD

**Issue by Etuldan** [Etuldan/MidiControl#21]
First chat text is not sent.

**Comment by sense-amr** [comment]
did you fix Twitch login ?

**Comment by Etuldan** [comment]
> did you fix Twitch login ?

Afaik, Twitch login was never broken for this repository.

**Comment by sense-amr** [comment]
it didnt work in the last version i tried .. but its working now with the latest..

**Comment by sense-amr** [comment]
https://user-images.githubusercontent.com/1504019/207810219-374f89f2-d7e8-4217-a4de-3aba507e6128.mp4

confirmed everything works :D
