### ISSUE TITLE
Resources.Designer.cs file is missing from git

### ISSUE THREAD

**Issue by Teeeeeep** [Etuldan/MidiControl#46]
Wish I could mark this as low priority but I'm new to Github and don't know how. The missing file Resources.Designer.cs can be generated with the right know-how, but pulling the source raw and loading it up leads to the MidiControl csproj failing to find the file in the MidiControl/Properties/ directory. VS will then mark all references to MidiControl.Properties in the designer as missing a reference until the file is regenerated.

Regenerating the file is easy, simply dirty the Resources.resx file and VS should recreate the Resources.Designer.cs file, but including it in the repo should also fix it.

**Comment by Etuldan** [comment]
As this file is autogenerated by a tool, the exclusion from git is intended.
Workflow to autogenerate binary is available here https://github.com/Etuldan/MidiControl/blob/obs-ws5.0/.github/workflows/dotnet-desktop.yml

**Comment by Teeeeeep** [comment]
Thanks so much for that info! I didn't pull this using the github app so that workspace yaml didn't get parsed by anything. Good things to know in the future <3

**Comment by Etuldan** [comment]
To be clear, the .yaml is not intended to be used manually, it's just a GitHub Actions file. But it show how the compilation is done.
