### ISSUE TITLE
OBS Bug/Put a LED feature for Launchpad mini

### ISSUE THREAD

**Issue by JaxzTW** [Etuldan/MidiControl#5]
When MIDIControl is open, after i finish a streaming if i want to close obs with that program open in background OBS crash with a memory error, i tried that a few times and i can now confirm that is not my problem, but an issue with MIDIControl when is on background/open.
And also if is possible, a LED feature for a launchpad, is really difficult to remember the hotkey on the launchpad when all the key are off 😅

**Comment by luxarts** [comment]
For the LED feedback you have this awesome guide https://www.partsnotincluded.com/how-to-control-the-leds-on-a-novation-launchkey-mini-ii/

Basically, you have to turn on InControl sending Note On in CHannel 1 with max velocity (`0x90 0x0C 0x7F`) and then you can send Note On in Channel 1 from C6 (`0x60`) to G#6 (`0x68`) for the first row or from E7 (`0x70`) to C8 (`0x78`) with a velocity between 0 (`0x00`, LED off) to 127 (`0x7F`, LED yellow). 

Example:
```
// Turn top-left LED red
0x90 0x60 0x0F

// Turn top-right LED green
0x90 0x68 0x7C

// Turn bottom-left LED orange
0x90 0x70 0x13

// Turn bottom-right LED yellow
0x90 0x78 0x7F
```

**Comment by JaxzTW** [comment]
> For the LED feedback you have this awesome guide https://www.partsnotincluded.com/how-to-control-the-leds-on-a-novation-launchkey-mini-ii/
> 
> 
> 
> Basically, you have to turn on InControl sending Note On in CHannel 1 with max velocity (`0x90 0x0C 0x7F`) and then you can send Note On in Channel 1 from C6 (`0x60`) to G#6 (`0x68`) for the first row or from E7 (`0x70`) to C8 (`0x78`) with a velocity between 0 (`0x00`, LED off) to 127 (`0x7F`, LED yellow). 
> 
> 
> 
> Example:
> 
> ```
> 
> // Turn top-left LED red
> 
> 0x90 0x60 0x0F
> 
> 
> 
> // Turn top-right LED green
> 
> 0x90 0x68 0x7C
> 
> 
> 
> // Turn bottom-left LED orange
> 
> 0x90 0x70 0x13
> 
> 
> 
> // Turn bottom-right LED yellow
> 
> 0x90 0x78 0x7F
> 
> ```
> 
> 

But i think i can't use two app on a midi device, like i can't use that app and also another app, so this have to be a feature into this app

**Comment by luxarts** [comment]
Yes, my comment was for @Etuldan.
I was watching the code and noticed that there is an implementation for this feature already but at least it doesn't work on my LaunchkeyMini MK2.

**Comment by mannaggacardarell** [comment]
For Led controll i think he can use this too: github.com/dbkynd/controlcast
I tried this old project and works good to control leds, but not compatible with my launchpad mk2

**Comment by Etuldan** [comment]
MIDIControl handle for the moment only a minimal LED feedback option.
Having the choice on the color/blink/... will be (maybe ?) a future options.
