### ISSUE TITLE
Add control of sources that are inside Group

### ISSUE THREAD

**Issue by RadioDM** [Etuldan/MidiControl#58]
Sources that are put inside a Group are not accessible in the MIDIControl. All I can do is to control the whole group itself, but not the individual sources.

**Comment by Etuldan** [comment]
Usage of OBS groups seems to be discouraged, according to : https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getgroupsceneitemlist
Nothing I can really do to 'fix' that.
Use nested scenes in OBS instead
