### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by DAL30200** [Etuldan/MidiControl#94]
Hi,

First of all, thank you for your program! I wanted to try to compile your program from the sources you provided but I have an error that I cannot resolve.
I have CS2034 errors: The type or namespace name 'Resource' does not exist in the namespace 'MidiControl.Properties' (are you missing an assembly reference?)
I did some research but couldn't find anything conclusive.
My version of Visual Studio Community 2022 is 17.8.5.
Is there any configuration to be done at the project level?

Thank you in advance for your answer.

(Sorry for the English, I did the translation with Google Translate, I'm French)

**Comment by Etuldan** [comment]
Hey !
You can look at the build sequences in the Github Actions, see https://github.com/Etuldan/MidiControl/blob/main/.github/workflows/build.yml
And for your issue : `.\ResGen.exe "D:\a\MidiControl\MidiControl\MidiControl\Properties\Resources.resx" /useSourcePath /str:csharp,MidiControl.Properties`

(et ne t'excuse pas de ton anglais car tu es Français, on a cette sale manie de dire ça alors qu'en vrai, bah probablement pas mal de monde passe par GoogleTranslate/Deepl, peut importe la langue maternelle ;) )

**Comment by DAL30200** [comment]
Merci pour ta réponse rapide ! Je voulais écrire en français car j'avais vu que tu étais Français mais je me suis dit que ce serait plus universel d'écrire en anglais !
Bon si j'ai bien compris il faut que je change dans le fichier build.yml le chemin de Resources.resx pour qu'il pointe vers la ou j'ai mis les sources ? Je dois le faire depuis notepad ou dans Visual ?
Désolé je suis informaticien mais plutôt orienté automatisme et supervision. j'ai pas l'habitude de me servir de Visual.

**Comment by Etuldan** [comment]
ResGen.exe should be included with your VSStudio tools. Run it with the arguments specified in the command line.

The build.yml file is used only by the Github actions to generate the program from the sources. But each command in it should be runnable in a local dev environment.
